import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Header, LayoutBlog } from "@repo/ui/index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen"`}
      >
        <LayoutBlog>
          <Header
            blog={{ url: "/blog", hasPrefetch: false }}
            admin={{ url: "/admin-panel", hasPrefetch: false }}
          />
          {children}
          <Footer />
        </LayoutBlog>
      </body>
    </html>
  );
}
