import { LayoutBlog, Header, Footer } from "@repo/ui/index";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const SHELL_ORIGIN =
  process.env.NEXT_PUBLIC_SHELL_ORIGIN ?? "http://localhost:3000";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen"`}
      >
        <LayoutBlog>
          <Header
            shellOrigin={SHELL_ORIGIN}
            blog={{ url: "/", hasPrefetch: true }}
            admin={{ url: "admin-panel", hasPrefetch: false }}
          />
          {children}
          <Footer />
        </LayoutBlog>
      </body>
    </html>
  );
}
